---
title: Microxanox - ...
author:
- name: Rainer M Krug
  email: Rainer.Krug@uzh.ch & Rainer@krugs.de
  affiliation: University of Zürich
  footnote: Corresponding Author
- name: Owen L. Petchey
  email: Owen.Petchey@ieu.uzh.ch
  affiliation: University of Zürich
address:
- code: University of Zürich
  address: Department of Evolutionary Biology and Environmental Studies, Winterthurerstrasse
    190, 8057 Zurich
keywords: metadata quality; data curation; archival; long term storage; R package;
abstract: |
  1. set the context for and purpose of the work;
  2. indicate the approach and methods;
  3. outline the main results;
  4. identify the conclusions and the wider implications.

journal: 'Ecology and Evolution - Applications'
bibliography: manuscript_bibliography.bib
date: "`r Sys.time()`"
output:
  html_document:
    df_print: paged
  rmarkdown::html_vignette: default
  pdf_document:
    keep_tex: yes
header-includes:
- \usepackage{lineno}
- \linenumbers
- \usepackage{setspace}
- \doublespacing
- \usepackage{fancyhdr}
- \fancyhead{}
- \fancyfoot{}
- \fancyhead[CO,CE]{Metadata made easy - the dmdScheme approach}
- \pagestyle{fancy}
vignette: |
  %\VignetteIndexEntry{Manuscript - microxanox} 
  %\VignetteEncoding{UTF-8} 
  %\VignetteEngine{knitr::rmarkdown}
nocite: '@bush2017'
linkcolor: blue
link-citations: yes
csl: methods-in-ecology-and-evolution.csl
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(microxanoxBeta)
```
  
# Journal Guidelines
  - Abstract < 350 words
  - Article 3000-4000 words

# Introduction

# The Model

# Implementation, Availability and Usage

# Use cases

# Conclusions


# References
