---
title: A study of the effects of within functional group diversity on the response
  to environmental change.
author: "Owen Petchey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Effects of within functional group diversity}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Setup R

```{r setup}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE, cache = FALSE,
                      fig.align = "centre", fig.width = 7, fig.height = 7)

library(tidyverse)
library(deSolve)
library(rootSolve)
library(here)
if (!require(microxanox)) {
  devtools::load_all(here::here())
}

## Set random number generator seed
## Is redundant if there are no stochastic components in the model
set.seed(13)

run_steadystate_sims <- TRUE
```


# Introduction

The aims here are:

* Reproduce the results of [Bush et al 2017](https://www.nature.com/articles/s41467-017-00912-x).

Please see the User manual vignette for further introduction and general methods.

# Methods

## Set defaults

```{r}
default_dynamic_model <- bushplus_dynamic_model_strains
## no default_parameter_values
## no default_initial_state
default_sim_duration <- 2000
default_sim_sample_interval <- 1
default_log10a_series <- c(log10(return_bushetal2017_parameter_values()["a_O"]),
                           log10(return_bushetal2017_parameter_values()["a_O"]))
default_event_definition <- event_definition_1_strains
default_event_interval <- 10
default_noise_sigma <- 0
default_minimum_abundances <- rep(1e2, 3)
names(default_minimum_abundances) <- c("CB", "PB", "SB") 
```


# Test results

## One strain per functional group

Constructing parameter set.

```{r}
CB_strain_params <- data.frame(strain_name = c("CB_1"),
                       g_max_CB = c(0.05),
                       k_CB_P = c(0.2),
                       h_SR_CB = c(300),
                       y_P_CB = c(1.67e8),
                       Pr_CB = c(6e-9),
                       m_CB = c(0.02),
                       i_CB = c(0))

PB_strain_params <- data.frame(strain_name = c("PB_1"),
                       g_max_PB = c(0.07),
                       k_PB_SR = 10,
                       k_PB_P = 0.5,
                       h_O_PB = 100,
                       y_SR_PB = 1.25e7,
                       y_P_PB = 1.67e8,
                       m_PB = 0.028,
                       i_PB = 0)

SB_strain_params <- data.frame(strain_name = c("SB_1"),
                       g_max_SB = c(0.1),
                       k_SB_SO = 5,
                       k_SB_P = 0.5,
                       h_O_SB = 100,
                       y_SO_SB = 3.33e7,  
                       y_P_SB = 1.67e8,
                       m_SB = 0.04,
                       i_SB = 0)
                       
all_other_params <- c(
  
  ## substrate diffusivity
  a_S = 0.001,
  a_O = 8e-4,
  a_P = 0.01,
  
  ## background substrate concentration
  back_SR = 300,
  back_SO = 300,
  back_O = 300,
  back_P = 9.5,
  
  ## oxidisation rate of reduced sulphur
  c = 4e-5
           
) 

one_strain_params <- construct_parameter_set(CB_strain_params,
                                    PB_strain_params,
                                    SB_strain_params,
                                    all_other_params)


one_strain_initial_state <- c(
  CB_1 = 5e1,
  PB_1 = 1e7,
  SB_1 = 1e7,
  SO = 300,
  SR = 300,
  O = 1e1,
  P = 1e1
  )
```


```{r eval = run_steadystate_sims}
simulation_result1 <- run_simulation(
               parameter_values = one_strain_params,
               initial_state = one_strain_initial_state)
save(simulation_result1, file = "data/multistrain1.Rda")

```


```{r}
load(file = "data/multistrain1.Rda")
plot_dynamics_strains(simulation_result1)


```



## Three strains per functional group

```{r}
num_CB_strains <- 3
num_PB_strains <- 3
num_SB_strains <- 3

CB_strain_params <- data.frame(strain_name = paste0("CB_", 1:num_CB_strains),
                       g_max_CB = rep(0.05, num_CB_strains),
                       k_CB_P = rep(0.2, num_CB_strains),
                       h_SR_CB = rep(300, num_CB_strains),
                       y_P_CB = rep(1.67e8, num_CB_strains),
                       Pr_CB = rep(6e-9, num_CB_strains),
                       m_CB = rep(0.02, num_CB_strains),
                       i_CB = rep(0, num_CB_strains))

PB_strain_params <- data.frame(strain_name = paste0("PB_", 1:num_PB_strains),
                       g_max_PB = rep(0.07, num_PB_strains),
                       k_PB_SR = rep(10, num_PB_strains),
                       k_PB_P = rep(0.5, num_PB_strains),
                       h_O_PB = rep(100, num_PB_strains),
                       y_SR_PB = rep(1.25e7, num_PB_strains),
                       y_P_PB = rep(1.67e8, num_PB_strains),
                       m_PB = rep(0.028, num_PB_strains),
                       i_PB = rep(0, num_PB_strains))

SB_strain_params <- data.frame(strain_name = paste0("SB_", 1:num_SB_strains),
                       g_max_SB = rep(0.1, num_SB_strains),
                       k_SB_SO = rep(5, num_SB_strains),
                       k_SB_P = rep(0.5, num_SB_strains),
                       h_O_SB = rep(100, num_SB_strains),
                       y_SO_SB = rep(3.33e7, num_SB_strains),  
                       y_P_SB = rep(1.67e8, num_SB_strains),
                       m_SB = rep(0.04, num_SB_strains),
                       i_SB = rep(0, num_SB_strains))

multi_strain_params <- construct_parameter_set(CB_strain_params,
                                    PB_strain_params,
                                    SB_strain_params,
                                    all_other_params)


multi_strain_initial_state <- c(
  CB_1 = 5e3,
  CB_2 = 1e3,
  CB_3 = 0,
  PB_1 = 1e7,
  PB_2 = 1e6,
  PB_3 = 1e5,
  SB_1 = 1e7,
  SB_2 = 1e6,
  SB_3 = 1e5,
  SO = 300,
  SR = 300,
  O = 1e1,
  P = 1e1)
```


```{r eval = run_steadystate_sims}
simulation_result3 <- run_simulation(
               parameter_values = multi_strain_params,
               initial_state = multi_strain_initial_state)
save(simulation_result3, file = "data/multistrain3.Rda")

```


```{r}
load(file = "data/multistrain3.Rda")
plot_dynamics_strains(simulation_result3)


```

