#' Extract \code{runsim_parameter} from \code{ss_by_a_N_parameter} 
#' 
#' Extract the parameter to run an individual simulation from either a parameter set for a 
#' steady state determinatuion (\code{ss_by_a_N()}) or the result set returned.
#' @param result  object of class \code{ss_by_a_N_parameter} as generated by \code{new_ss_by_a_N_parameter()}
#' @param i Index of the individual simulatio to extract the parameter for
#' 
#' @return an object of class \code{ss_by_a_N_parameter}
#' @export
get_ssbyaN_parameter <- function(result, i) { 
  
  parameter <- result
  
  ## set the oxygen diffusivity in the parameters to the required value
  parameter$a_O <- parameter$ss_expt[i, ]["a_O"]
  
  ## and set all the initial states in the parameter object to the required values
  CBs <- unlist(rep(parameter$ss_expt[i, ]["N_CB"] / length(grep("CB", names(parameter$strain_parameter$initial_state))),
                    length(grep("CB", names(parameter$strain_parameter$initial_state)))))
  names(CBs) <- NULL
  parameter$strain_parameter$initial_state[grep("CB", names(parameter$strain_parameter$initial_state))] <- CBs
  
  PBs <- unlist(rep(parameter$ss_expt[i, ]["N_PB"] / length(grep("PB", names(parameter$strain_parameter$initial_state))),
                    length(grep("PB", names(parameter$strain_parameter$initial_state)))))
  names(PBs) <- NULL
  parameter$strain_parameter$initial_state[grep("PB", names(parameter$strain_parameter$initial_state))] <- PBs
  
  SBs <- unlist(rep(parameter$ss_expt[i, ]["N_SB"] / length(grep("SB", names(parameter$strain_parameter$initial_state))),
                    length(grep("SB", names(parameter$strain_parameter$initial_state)))))
  names(SBs) <- NULL
  parameter$strain_parameter$initial_state[grep("SB", names(parameter$strain_parameter$initial_state))] <- SBs
  
  ## update forcing series with the required oxygen diffus. value
  parameter$log10a_series <- c(
    log10(parameter[["a_O"]]),
    log10(parameter[["a_O"]])
  )
  
  parameter$result <- NULL
  
  class(parameter) <- grep( "ss_by_a_N_result", class(parameter), value = TRUE, invert = TRUE)
  
  return(parameter)
}