#' Get the steady state solutions for a set of oxygen diffusivity and initial states.
#' Probably best to not use this directly, but rather via the function \code{ss_by_a_N()}
#' 
#'
#' @param x A vector of oxygen diffusivity and initial conditions.
#' @param parameter  object of class \code{ss_by_a_N_parameter} as generated by \code{new_ss_by_a_N_parameter()}
#' 
#' @return A vector of steady states
#' @export
get_final_states_a_N <- function(x, parameter) { 
  
  ## set the oxygen diffusivity in the parameters to the required value
  parameter$a_O <- x["a_O"]
  
  ## and set all the initial states in the parameter object to the required values
  CBs <- unlist(rep(x["N_CB"] / length(grep("CB", names(parameter$strain_parameter$initial_state))),
      length(grep("CB", names(parameter$strain_parameter$initial_state)))))
  names(CBs) <- NULL
  parameter$strain_parameter$initial_state[grep("CB", names(parameter$strain_parameter$initial_state))] <- CBs
    
  PBs <- unlist(rep(x["N_PB"] / length(grep("PB", names(parameter$strain_parameter$initial_state))),
                    length(grep("PB", names(parameter$strain_parameter$initial_state)))))
  names(PBs) <- NULL
  parameter$strain_parameter$initial_state[grep("PB", names(parameter$strain_parameter$initial_state))] <- PBs
  
  SBs <- unlist(rep(x["N_SB"] / length(grep("SB", names(parameter$strain_parameter$initial_state))),
                    length(grep("SB", names(parameter$strain_parameter$initial_state)))))
  names(SBs) <- NULL
  parameter$strain_parameter$initial_state[grep("SB", names(parameter$strain_parameter$initial_state))] <- SBs
  
 ## update forcing series with the required oxygen diffus. value
  parameter$log10a_series <- c(
    log10(parameter[["a_O"]]),
    log10(parameter[["a_O"]])
  )
  
  parameter$initial_state = parameter$strain_parameter$initial_state
  ## run the simulation
  simres <- run_simulation(
    parameter
  #   dynamic_model = bushplus_dynamic_model,
  #   initial_state = parameter$initial_state,
  #   parameter_values = parameter,
  #   sim_duration = ssfind_simulation_duration,
  #   sim_sample_interval = ssfind_simulation_sampling_interval,
  #   event_interval = ssfind_event_interval,
  #   log10a_series = ss_log10a_series,
  #   minimum_abundances = ssfind_minimum_abundances
  )
  ## return only the final values of the state variables
  
  simres$result[2,-1] 
  
}