#' Get the steady state solutions for a set of oxygen diffusivity and initial states.
#'
#' Can be used directly. Also can be used indirectly, via the function \code{run_replication_ssfind_parameter()}
#' @param x A vector of oxygen diffusivity and initial conditions.
#' @param parameter  object of class \code{replication_ssfind_parameter} as generated by \code{new_replication_ssfind_parameter()}
#'
#' @return A vector of steady states
#' @export
get_final_states_a_N <- function(
  x,
  parameter
){

  ## set the oxygen diffusivity in the parameters to the required value
  parameter$a_O <- x["a_O"]

  ## and set all the initial states in the parameter object to the required values
  CBs <- unlist(
    rep(
      x["N_CB"] / length(grep("CB", names(parameter$strain_parameter$initial_state))),
      length(grep("CB", names(parameter$strain_parameter$initial_state)))
    )
  )
  names(CBs) <- NULL
  parameter$strain_parameter$initial_state[grep("CB", names(parameter$strain_parameter$initial_state))] <- CBs

  PBs <- unlist(
    rep(
      x["N_PB"] / length(grep("PB", names(parameter$strain_parameter$initial_state))),
      length(grep("PB", names(parameter$strain_parameter$initial_state)))
    )
  )
  names(PBs) <- NULL
  parameter$strain_parameter$initial_state[grep("PB", names(parameter$strain_parameter$initial_state))] <- PBs

  SBs <- unlist(
    rep(
      x["N_SB"] / length(grep("SB", names(parameter$strain_parameter$initial_state))),
      length(grep("SB", names(parameter$strain_parameter$initial_state)))
    )
  )
  names(SBs) <- NULL
  parameter$strain_parameter$initial_state[grep("SB", names(parameter$strain_parameter$initial_state))] <- SBs

 ## update forcing series with the required oxygen diffus. value
  parameter$log10a_series <- c(
    log10(parameter[["a_O"]]),
    log10(parameter[["a_O"]])
  )

  ## run the simulation
  simres <- run_simulation(
    parameter
  )

  ## return only the final values of the state variables
  simres$result[2,-1]

}