# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "times", # <event_definition_1>
  "state", # <event_definition_1>
  "parameters", # <event_definition_1>
  "Quantity", # <get_stability_measures>
  "starts_with", # <get_stability_measures>
  "direction", # <get_stability_measures>
  "up", # <get_stability_measures>
  "down", # <get_stability_measures>
  "a_O", # <get_stability_measures>
  "a", # <get_stability_measures>
  "a", # <plot_dynamics>
  "species", # <plot_dynamics>
  "quantity", # <plot_dynamics>
  "functional_group", # <plot_dynamics>
  "log10_quantity", # <plot_dynamics>
  "var_type", # <plot_dynamics>
  ".", # <plot_dynamics>
  "time", # <plot_dynamics>
  NULL
))
