# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "Quantity", # <get_stability_measures.replication_ssfind_result>
  "starts_with", # <get_stability_measures.replication_ssfind_result>
  "direction", # <get_stability_measures.replication_ssfind_result>
  "up", # <get_stability_measures.replication_ssfind_result>
  "down", # <get_stability_measures.replication_ssfind_result>
  "a_O", # <get_stability_measures.replication_ssfind_result>
  "a", # <get_stability_measures.replication_ssfind_result>
  "Quantity", # <get_stability_measures.temporal_ssfind_result>
  "starts_with", # <get_stability_measures.temporal_ssfind_result>
  "direction", # <get_stability_measures.temporal_ssfind_result>
  "up", # <get_stability_measures.temporal_ssfind_result>
  "down", # <get_stability_measures.temporal_ssfind_result>
  "a_O", # <get_stability_measures.temporal_ssfind_result>
  "a", # <get_stability_measures.temporal_ssfind_result>
  "Species", # <get_stability_measures.temporal_ssfind_result>
  "time", # <get_stability_measures.temporal_ssfind_result>
  "species", # <plot_dynamics>
  "quantity", # <plot_dynamics>
  ".", # <plot_dynamics>
  "functional_group", # <plot_dynamics>
  "time", # <plot_dynamics>
  "log10_quantity", # <plot_dynamics>
  "var_type", # <plot_dynamics>
  "", # <plot_dynamics_symmetric>
  "", # <sym_plot_temporal_ss>
  "time", # <run_temporal_ssfind>
  "pars", # <run_temporal_ssfind_experiment>
  "ssfind_pars", # <run_temporal_ssfind_experiment>
  NULL
))
